-- CreateEnum
CREATE TYPE "GraphType" AS ENUM ('MULTIPLE_FAILED_LOGINS', 'UNUSUAL_LOCATIONS', 'HIGH_VELOCITY_PASSWORD_GUESS', 'IP_ADDRESSES_TARGETING_MULTIPLE_ACCOUNTS', 'GEOGRAPHICALLY_IMPOSSIBLE_LOGINS', 'TRAVEL_VELOCITY_ANALYSIS');

-- CreateTable
CREATE TABLE "Graph" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "GraphType" NOT NULL,
    "data" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Graph_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Graph_userId_type_key" ON "Graph"("userId", "type");

-- AddForeignKey
ALTER TABLE "Graph" ADD CONSTRAINT "Graph_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
